#!/usr/bin/env bash
set -euo pipefail

# Build a minimal macOS binary for testing notarization and generate a Go source file
# This script is called by `go generate` from binary.go

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$SCRIPT_DIR/bin"
BINARY_FILE="$BIN_DIR/test_notarize_hello.macho"
GO_FILE="$SCRIPT_DIR/binary_gen.go"

echo "Building test hello world binary..."

# build for darwin/arm64 (Apple Silicon)
cd "$BIN_DIR/hello"
GOOS=darwin GOARCH=arm64 go build -o "$BINARY_FILE" -ldflags="-s -w" .

echo "Generated test_notarize_hello.macho ($(wc -c < "$BINARY_FILE") bytes)"

echo "Generating Go source file..."

# generate Go source file with embedded binary bytes
# note: xxd -i output needs a trailing comma on the last line for valid Go syntax
{
    echo "// Code generated by generate.sh. DO NOT EDIT."
    echo ""
    echo "package notarizetest"
    echo ""
    echo "var binaryBytes = []byte{"
    xxd -i < "$BINARY_FILE" | sed 's/^/	/' | sed '$ s/$/,/'
    echo "}"
} > "$GO_FILE"

echo "Generated binary_gen.go"
