#!/usr/bin/env bash
set -euo pipefail

# Build a minimal macOS binary using Zig (via Docker) and generate a Go source file
# This script is called by `go generate` from binary.go

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE_DIR="$SCRIPT_DIR/image"
BINARY_FILE="$SCRIPT_DIR/bin/hello.macho"
GO_FILE="$SCRIPT_DIR/binary_gen.go"
IMAGE_NAME="quill-notarize-test-bin"

echo "Building minimal macOS binary with Zig (via Docker)..."

# build the Docker image containing the compiled binary
docker build -t "$IMAGE_NAME" "$IMAGE_DIR"

# extract the binary from the image
container_id=$(docker create "$IMAGE_NAME" /hello)
docker cp "$container_id:/hello" "$BINARY_FILE"
docker rm "$container_id" > /dev/null

echo "Generated hello.macho ($(wc -c < "$BINARY_FILE" | tr -d ' ') bytes)"

echo "Generating Go source file..."

# generate Go source file with embedded binary bytes
# note: xxd -i output needs a trailing comma on the last line for valid Go syntax
{
    echo "// Code generated by generate.sh. DO NOT EDIT."
    echo ""
    echo "package notarizetest"
    echo ""
    echo "var binaryBytes = []byte{"
    xxd -i < "$BINARY_FILE" | sed 's/^/	/' | sed '$ s/$/,/'
    echo "}"
} > "$GO_FILE"

echo "Generated binary_gen.go ($(wc -c < "$GO_FILE" | tr -d ' ') bytes)"
